require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - 'config/**/*.rb'
    - 'bin/**/*'

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Style/MethodCallWithArgsParentheses:
  Exclude:
    - 'spec/**/*.rb'
